name: Test and Deploy

on:
  push:
    branches:
      - main

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Greeting
        run: echo hiya!
    
   test-utils:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and Clone
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Test utils
        run: npm run test-utils


